name: Deploy and Bump

on:
  push:
    branches:
      - master
    paths:
      - 'packages/app/**'
      - 'packages/functions/**'

jobs:
  bump:
    name: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email rafaelfr@outlook.com
          git config --global user.name Rafael Franco
      - name: Install dependencies
        run: yarn
      - name: bump
        run: |
          yarn lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
