name: Deploy and Bump

on:
  push:
    branches:
      - master

jobs:
  bump:
    name: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure CI Git User
        run: |
          git config --global user.email rafaelfr@outlook.com
          git config --global user.name Rafael Franco
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: |
          GH_TOKEN=${GH_TOKEN}
          yarn lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
